### ISSUE TITLE
Rake db:create fails on Linux

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/sinatra-user-auth#37]
# Issue

When running on a local Linux Env or in the IDE, executing `rake db:create` is met with the following error: 

> [13:39:26] (master) sinatra-user-auth-v-000
// ♥ rake db:create
WARNING: If you plan to load any of ActiveSupport's core extensions to Hash, be
sure to do so *before* loading Sinatra::Application or Sinatra::Base. If not,
you may disregard this warning.
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: []
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/tasks/database_tasks.rb:109:in `create_current'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/activerecord-4.2.0/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/home/aspen/.rvm/gems/ruby-2.3.7/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/aspen/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `eval'
/home/aspen/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

## Replication 

This was replicated on my instance of the IDE, as well as on my local machine running Ubuntu 18.10. 
Attempted with Ruby versions 2.3.1, 2.3.3, and 2.3.7, all met with the same error. 

## Solution

The solution was creating an explicit `database.yml` file within the `config` directory. This is a fairly advanced issue and solution for students at this level of the curriculum, and should be acknowledged as moving from IDE to local environment is not advised until a later lesson. 

Example `database.yml` file below: 
```
development:
  adapter: sqlite3
  database: db/user_authdevelopment.sqlite
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/user_authtest.sqlite
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/user_authproduction.sqlite
  pool: 5
  timeout: 5000
```
#Staff
